language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="mustache"
  - PINS="mustache:."
  matrix:
  - DISTRO="ubuntu-lts" OCAML_VERSION="4.08"
  - DISTRO="ubuntu-lts" OCAML_VERSION="4.09"
  - DISTRO="ubuntu-lts" OCAML_VERSION="4.10"
  - DISTRO="ubuntu-lts" OCAML_VERSION="4.11"
